--CREATE DATABASE CoursesDB;
--USE CoursesDB;

--CREATE TABLE Course(
--ID int Identity(1,1) NOT NULL Primary Key,
--GEOutcomes NVARCHAR(80),
--Cat NVARCHAR(50),
--CatDes NVARCHAR(3),
--CourseNumber NVARCHAR(255),
--Credits SMALLINT,
--CourseName NVARCHAR(255),
--Equivalent NVARCHAR(50),
--Prereqs NVARCHAR(350),
--Note NVARCHAR(350),
--[Description] NVARCHAR(3000)
--);

--SELECT * FROM Course;

--------Drop Table Course;

INSERT INTO Course(GEOutcomes, Cat, CatDes, CourseNumber, Credits, CourseName, Equivalent, Prereqs, Note, [Description] )
VALUES 
----Accounting
--(Null, 'Accounting', 'ACC', 'ACC 1500', 3, 'Accounting for the Small Business Owner', 'ACC 1110', Null, Null, 'This course is designed for the non-accountant business owner. The student will study accounting procedures and applications for small businesses. Topics include bookkeeping for the small business, accounting systems for the small business, understanding of financial statements, overview of inventory management, survey of small business owner tax concerns and accounting concepts relating to financing the small business.'),
--(Null, 'Accounting', 'ACC', 'ACC 1800', 2, 'Accounting Procedures', NULL, Null, Null, 'This course presents general accounting procedures. Students will study the accounting equation, emphasizing the process of analyzing and recording financial information using the double-entry accounting system. Coverage includes the recording of basic transactions and adjustments for both service and merchandising concerns.'),
--(Null, 'Accounting', 'ACC', 'ACC 1803', 2, 'Accounting with Quickbooks', 'ACC 2230, ACC 2230', 'ACC 1500 or ACC 1800 with a ''C'' or better within the last three years.', 'Prerequisites for courses in this department are not automatically waived for College Guest students and students with a bachelor''s degree or higher from a U.S. institution.', 'This course provides an overview of payroll, record-keeping regulations, reporting requirements, accounting procedures and federal labor laws. The course includes computations of gross wages, salaries, mandatory deductions of federal, state and local taxes, and optional deductions. Also covered is employer related taxes and preparation of various payroll tax forms.'),
--(Null, 'Accounting', 'ACC', 'ACC 1805', 2, 'Accounting with Quickbooks', Null, 'ACC 1500 or ACC 1800 with a ''C'' or better within the last three years.', 'Prerequisites for courses in this department are not automatically waived for College Guest students and students with a bachelor''s degree or higher from a U.S. institution.', 'This course will expose students to the popular accounting software, Quickbooks. The course reinforces basic accounting procedures through the use of Quickbooks. The student will use Quickbooks to enter accounts receivable and accounts payable transactions and to generate financial reports.'), 
--(Null, 'Accounting', 'ACC', 'ACC 1810', 4, 'Principles of Financial Accounting', 'ACC 2510', 'ACC 1500 or ACC 1800 with a ''C'' or better within the last three years.', 'Prerequisites for courses in this department are not automatically waived for College Guest students and students with a bachelor''s degree or higher from a U.S. institution.', 'This course reviews basic financial accounting principles covering the accounting cycle. Topics include: cash, investments, receivables and payables, inventory valuation, fixed and intangible assets valuation, current and long term liabilities, and owner''s equity. Internal control and financial statement analysis is also considered. Emphasis is placed on the corporate form of ownership.'),
--(Null, 'Accounting', 'ACC', 'ACC 1820', 4, 'Principles of Managerial Accounting', 'ACC 2520', 'ACC 1810 with a ''C'' or better within the last three years.', 'Prerequisites for courses in this department are not automatically waived for College Guest students and students with a bachelor''s degree or higher from a U.S. institution.', 'This course emphasizes the managerial aspects of cost accounting for manufacturing and service entities. Managerial topics will include: cost terms and behavior, determination of the cost of goods manufactured and sold, job order and process cost accounting, cost-volume-profit analysis, variable costing, profit planning and budgeting, standard costs and variance analysis, capital budgeting, and the Statement of Cash Flows.'),
--(Null, 'Accounting', 'ACC', 'ACC 2070', 2, 'Cost Accounting', 'ACC 2040,  ACC 2020', 'ACC 1810 with a ''C'' or better within the last three years.', 'Prerequisites for courses in this department are not automatically waived for College Guest students and students with a bachelor''s degree or higher from a U.S. institution.', 'This intermediate level course reviews and further develops material presented in Managerial Accounting. Additional topics presented include: activity based costing, quality and just-in-time issues, the theory of constraints, pricing decisions and cost management, cost allocation, management control systems and performance measurement.'),
--(Null, 'Accounting', 'ACC', 'ACC 2210', 2, 'Computerized Accounting', 'ACC 2710', 'ACC 1810 with a ''C'' or better within the last three years and CIS 1050.', 'Prerequisites for courses in this department are not automatically waived for College Guest students and students with a bachelor''s degree or higher from a U.S. institution.', 'The student will be exposed to microcomputer skills as used in accounting and business. The course reinforces financial accounting concepts and procedures through use of personal computers and popular commercial software. The student will use a commercial general ledger software package to cover topics such as: the general ledger, accounts receivable, accounts payable, payroll, adjusting and closing entries. The student will use spreadsheets and/or other appropriate software for report preparation and solution of typical accounting related problems.'),

----Anthropology
--('Global Understanding and Responsibility', 'Anthropology', 'ANT', 'ANT 1540', 3, 'Introduction to Cultural Anthropology', Null, Null, Null, 'This course will develop students'' understanding of culture through examining cultural forms throughout the world. This course is an introduction to anthropological methods, theories and ethnographic studies that evaluate the integrated and holistic nature of culture. We examine cultural ideas and practices in art, religion, gender, politics, economics, and kinship among others. This course emphasizes the importance of diverse cultures for developing an understanding of strategies, perspectives and conditions in the human experience.'),
--('Scientific Literacy', 'Anthropology', 'ANT', 'ANT 1550', 3, 'Introduction to Biological Anthropology', 'ANT 1520, ANT 1520', Null, Null, 'In this course we will examine human biology and evolution through the analyses of the fossil record, evolutionary forces, and the human genome. This course explores contemporary scientific explanations about human origins, biological change and related primate species thorough examining physiology, cognition and morphology. This course will introduce students to the methods and theories in biological anthropology, human evolution, archaeology and paleoanthropology.'),
--(Null, 'Anthropology', 'ANT', 'ANT 2520', 3, 'Special Topics in Anthropology', Null, 'ANT 1540', Null, 'Topics courses are designed to examine specializations in research within the various fields of anthropology. Refer to the specific section using OCC''s online system for current topics.'),
--(Null, 'Anthropology', 'ANT', 'ANT 2530', 3, 'Special Topics in Anthropology', Null, 'ANT 1540',  Null, 'Topics courses are designed to examine specializations in research within the various fields of anthropology. Refer to the specific section using OCC''s online system for current topics.'),
--(Null, 'Anthropology', 'ANT', 'ANT 2540', 3, 'Special Topics in Anthropology', Null, 'ANT 1540', Null, 'Topics courses are designed to examine specializations in research within the various fields of anthropology. Refer to the specific section using OCC''s online system for current topics.'),
--(Null, 'Anthropology', 'ANT', 'ANT 2550', 3, 'Special Topics in Anthropology', Null, 'ANT 1540',  Null, 'Topics courses are designed to examine specializations in research within the various fields of anthropology. Refer to the specific section using OCC''s online system for current topics.'),
--(Null, 'Anthropology', 'ANT', 'ANT 2560', 3, 'Special Topics in Anthropology', Null, 'ANT 1540', Null, 'Topics courses are designed to examine specializations in research within the various fields of anthropology. Refer to the specific section using OCC''s online system for current topics.'),
--('Global Understanding and Responsibility', 'Anthropology', 'ANT', 'ANT 2570', 2, 'Myth, Magic and the Anthropology of Religion', Null, Null, Null, 'In this course, we examine religious beliefs and practices through primary anthropological research and cross-cultural comparison. We explore foundational religious topics like myth, symbols, magic, witchcraft, religious rituals, specialists, God(s) and other concepts related to the analysis of the supernatural. This course introduces students to the anthropology of religion, its studies, theories, concepts and ethnographic research. Through analysis of religious rituals and beliefs we are able to connect religion to other cultural phenomena of art, music and literature (and others) that enrich the human experience. '),

----Apprentice Applied Technology
--(Null, 'Apprentice Applied Technology', 'APP', 'APP 2170', 4, 'Applied Technology', 'APP 8160, APP 8150', 'MAT 1050 or placement into MAT 1100 or higher; or consent of instructor.', Null, 'This course is designed to prepare students for technical careers. The complexity and rapid change of modern technology require training that is applicable to more than a single job. Technicians will be exposed to the concepts of the mechanical, fluid, electrical and thermal principles on which modern technology is based. This course integrates the above mentioned four concepts with the physical principles of force, work, rate, resistance, energy, power and force transformers. This material is taught by lecture, video tape and lab demonstrations to reinforce the concepts of technical physics. '),

------Apprentice Engineering / Drafting
--(Null, 'Apprentice Engineering / Drafting', 'TED', 'TED 1030', 3, 'Basic Blueprint Reading', Null, Null, Null, 'The student will learn a series of related steps leading to an understanding of shop blue-prints, with emphasis placed on the interpretation of blueprints, performing mathematical computations, basic blueprint terminology and sketching various views of pictorial and orthographic drawings.'),

----Apprentice Mathematics
--(Null, 'Apprentice Mathematics', 'APM', 'APM 8110', 3, 'Geometry Algebra', Null, 'Secondary school algebra', Null, 'This course will provide the student with the fundamentals of Algebra and Geometry as applied to practical industrial problems that arise in his or her trade area. Topics include positive and negative numbers, ratio and proportion, simple equations, percentage, tapers, square root, formulas, and quadratic equations. Geometry principles of axioms, propositions, circle definitions, central angles, and tangents will be applied in the problem solving techniques of actual trade problems. '),
--(Null, 'Apprentice Mathematics', 'APM', 'APM 8210', 3, 'Plane Trigonometry', Null, 'APM 8110 or equivalent', Null, 'This course provides the student with the basic principles of trigonometry as applied to industrial problems. Topics covered are basic trigonometric functions, functions of angles, relations between trigonometric functions, tables and their uses, and solution of right angles. It will also cover the interpolation of angles to the nearest second of a degree, solution of oblique triangles by right triangle methods, Law of Sines, and Law of Cosines'),
--(Null, 'Apprentice Mathematics', 'APM', 'APM 8310', 4, 'Advanced Trigonometry and Angle Calculations for Industry', Null, 'APM 8210', Null, 'This course provides students with advanced applications of trigonometry and compound angles to solve for out of shape features of solids. Trigonometric and compound angle formulas will be used to create definite values of solids containing out of shape features essential to measure and locate details on a blueprint. Students will use advanced mathematical calculations to transform blueprints from art to part. Students will learn how trigonometric and angular computations apply to setting up various materials for machining and checking in today''s shop environment. Students will learn the principles of CNC machining that are applied in creating accurate representations of shaped features. Students will gain the knowledge of many methods of checking these figures for accuracy.'),

----Apprentice Tinsmith
--(Null, 'Apprentice Tinsmith', 'APT', 'APT 8310', 2, 'Industrial Safety', Null, Null, Null, 'Work place safety based upon OSHA standards is addressed in this course. Topics will include rigging, personal safety equipment, lock-out tag-out procedures, use of ladders, confined space entry, and hazardous environments. Students will demonstrate appropriate behaviors while performing work place activities under the supervision of the instructor. This course fulfills; Ten (10) contact hours of OSHA/Safety Awareness, and Fifteen (15) contact hours of Industry Orientation (Michigan Laws & Rules) for State of Michigan registered Electrical Apprentices for a total of twenty five (25) contact hours.'),

----Arabic
--('Effective Communication', 'Arabic', 'ARB', 'ARB 1510', 4, 'Beginning Arabic I', Null, Null, Null, 'This is an introductory course with special emphasis on the fundamentals of speaking, listening, reading, writing and understanding Arabic language and culture. The course will introduce basic Arabic linguistic structure according to functional models, which can be applied to everyday conversational situations. '),
--('Effective Communication', 'Arabic', 'ARB', 'ARB 1530', 4, 'Beginning Arabic II', Null, 'ARB 1510 or equivalent', Null, 'This course, which is a continuation of ARB 1510, comprises the second half of the introduction to Arabic. The course will emphasize the fundamentals of speaking, listening, reading, writing and understanding of Arabic language and culture according to functional models, which can be applied to everyday conversational situations.'),

------Art
--('Aesthetic Awareness', 'Art', 'ART', 'ART 1510', 3, 'Basic Drawing', 'ART 1010', Null, Null, 'The student will demonstrate the use of various drawing techniques including contour drawings, continuous lines, shadow-mass impressions, and expressive line quality. The student will identify and analyze the structure of form and render a drawing on the basis of these observations.'),
--('Aesthetic Awareness', 'Art', 'ART', 'ART 1520', 3, 'Basic Design', 'ART 1020', Null, Null, 'The student will develop skills that are fundamental in understanding design in two and three-dimensional aspects. The student will be assigned various problems where the specific use of media and its objectives are outlined, viewed from its functional and aesthetic importance.'),
--('Aesthetic Awareness', 'Art', 'ART', 'ART 1530', 3, 'Acrylic Painting', Null, Null, Null, 'The student will develop an understanding of acrylic painting medium by exploring a multi-media approach to painting. Students will demonstrate competency in handling figurative and non-figurative subjects, montage, collage, impasto build-up, and other related technical problems.'),
--('Aesthetic Awareness', 'Art', 'ART', 'ART 1540', 3, 'Introduction to Ceramics', 'ART 1300', Null, Null, 'This course covers the basic nature and properties of clay, applying hand-building techniques, and a select range of decorating and ceramic firing processes. Students will develop an awareness of how elements and principles of design integrate into functional and sculptural ceramic form. Historical and contemporary ceramic sources are explored. '),
--('Aesthetic Awareness', 'Art', 'ART', 'ART 1550', 3, 'Sculpture', 'ART 1350', Null, Null, 'The student will create several sculptures utilizing a variety of materials such as plaster, wood, stone, metal, and plastics. A variety of techniques and philosophies will be explored'),
--('Aesthetic Awareness', 'Art', 'ART', 'ART 1560', 3, 'Art Appreciation', Null, Null, Null, 'Students are introduced to the visual arts in relation to their cultures and societies. The course includes arts of various times and places, aesthetic orientations that affect them and individual artists'' relationship to their environments. The class connects artistic expressions and their aesthetic orientations with philosophical, religious, political and/or socio-economic influences.'),
--('Aesthetic Awareness', 'Art', 'ART', 'ART 1570', 3, 'Oil Painting', Null, Null, Null, 'The student will develop skills requisite to oil painting based on a systematic approach to fundamental techniques and philosophies utilizing such media as slides, films, and laboratory reading, supplemented by gallery participation and discussion. In the studio, emphasis will be placed on materials and concepts while encouraging personal and creative production'),
--('Aesthetic Awareness', 'Art', 'ART', 'ART 1600', 3, 'Watercolor Painting', 'ART 1610 or consent of instructor.', Null, Null, 'The student will develop skills in the transparent water color medium based on fundamental and experimental techniques. The many watercolor styles will be investigated utilizing slides, films, and readings, supplemented by gallery participation and discussion. In the studio, emphasis will be placed on the spontaneity and immediacy of watercolor while encouraging personal and creative production.'),
--('Aesthetic Awareness', 'Art', 'ART', 'ART 1610', 3, 'Jewelry', Null, Null, Null, 'Jewelry offers the basic techniques of metal work, allowing the student opportunity to create attractive jewelry or small objects by sawing, soldering, fusion, and forging in various metals.'),
--(Null, 'Art', 'ART', 'ART 1611', 3, 'Advanced Jewelry', Null, Null, Null, 'Advanced Jewelry offers the student an opportunity to learn methods of casting in precious metals from original wax models. Work will include centrifugal casting, burning out, finishing, and gemstone setting.'),
--(Null, 'Art', 'ART', 'ART 2110', 3, 'Wheel Throwing I: Introduction to the Potter''s Wheel', 'CER 1210', Null, Null, 'This course teaches the basic techniques of throwing on the potter''s wheel. Shaping of tall and low forms will be emphasized.'),
--(Null, 'Art', 'ART', 'ART 2120', 3, 'Wheel Throwing II', 'CER 1221, CER 1220', 'ART 2110 or consent of instructor', Null, 'Building upon the skills developed in Wheel Throwing I, this course emphasizes more complex forms including lids, handles, and closed forms.'),
--(Null, 'Art', 'ART', 'ART 2130', 3, 'Wheel Throwing III', 'CER 2230', 'ART 2110 or consent of instructor', Null, 'This course builds upon the skills learned in Wheel Throwing I. Alternative approaches and techniques will be taught using the potter''s wheel to achieve both functional and sculptural forms.'),
--(Null, 'Art', 'ART', 'ART 2140', 3, 'Wheel Throwing IV', 'CER 2240', 'ART 2110 or consent of instructor', Null, 'Building on the skills learned in Wheel Throwing III, this course will introduce students to techniques used in production of multiple objects of similar size and construction of complex forms.'),
--('Aesthetic Awareness', 'Art', 'ART', 'ART 2240', 3, 'Ceramics: Intermediate Hand-Building', 'ART 2540, ART 2300', Null, Null, 'Intermediate Hand-Building builds upon basic methods and processes learned in ART 1540. Students will learn advanced methods of construction based on coursework that addresses functional and sculptural ceramic objects, while continuing to further develop an understanding of historical and contemporary ceramics. ART 1540 is highly recommended, but not required.'),
--(Null, 'Art', 'ART', 'ART 2250', 3, 'Ceramics: Advanced Hand-Building', 'CER 2320', 'ART 2240 or consent of instructor', Null, 'Advanced Hand-Building builds upon methods and processes learned during Intermediate Hand-Building. This course approaches experimental and advanced techniques in fabricating and considering sculptural and functional ceramic form. Discourse and research around contemporary and historical ceramics will continue to be developed.'),
--(Null, 'Art', 'ART', 'ART 2260', 3, 'Ceramic Field Study', 'CER 2211, CER 2210', 'Consent of instructor', Null, 'Ceramic Field Study will permit students to concentrate their learning experiences in one special area of interest. This can be an in-depth experience in an area not ordinarily covered in other ceramic courses.'),
--(Null, 'Art', 'ART', 'ART 2270', 3, 'Ceramics: Glaze Formulation', 'CER 2410', Null, Null, 'The purpose of this course is to provide an introduction to making glazes. It will help students to learn the basic ingredients used for glazes and how they react in the batch formula.'),
--(Null, 'Art', 'ART', 'ART 2510', 3, 'Fundamentals of Figure Drawing', 'ART 2010', 'ART 1510 or consent of instructor', Null, 'The student will develop skills, primarily in black and white media, of rendering an artist''s understanding of anatomy. Students will concentrate on proportions, form, and portrait studies.'),
--(Null, 'Art', 'ART', 'ART 2520', 3, 'Advanced Drawing', 'ART 2020', 'ART 1510', Null, 'Working with a thorough understanding of proportion and form, the student will gain skills in a creative approach to the visual image. These skills will be facilitated through the use of watercolor, pastel, charcoal, and ink washes.'),
--(Null, 'Art', 'ART', 'ART 2550', 3, 'Advanced Sculpture', 'ART 2530', 'ART 1550', Null, 'The student will create a minimum of two sculptures equal in time value to 45 hours each from a variety of media including welding, bronze casting, fiberglass construction, and outdoor cement sculpture. Emphasis will be placed on creative involvement in seeking a personal expression'),
--(Null, 'Art', 'ART', 'ART 2570', 3, 'Advanced Design', Null, 'ART 1520', Null, 'The student will complete a variety of assignments dealing with various facets of functional and non-functional design, including forms and techniques of media application and two and three-dimensional projects utilizing paint, plaster, and/or plastics.'),
--('Aesthetic Awareness', 'Art', 'ART', 'ART 2600', 3, 'American Art', Null, Null, Null, 'The course presents American visual arts from the colonial period to the present time with emphasis on modern/contemporary expressions. The class is designed to show the uniquely American character of these arts as they reflect American life and the varied cultural influences that affect it.'),
--(Null, 'Art', 'ART', 'ART 2630', 3, 'Advanced Oil Painting', Null, 'ART 1570 or consent of instructor', Null, 'The student will further develop his/her skills and abilities toward a better understanding of the oil painting medium. The student will continue his/her investigation of oil painting by viewing slides and films, by reading art books and periodicals, and by attending galleries and museums followed by periodic class critiques. In the studio, emphasis will be placed on techniques and design qualities (formal elements) which are necessary ingredients to produce a well-composed painting while encouraging personal and creative growth.'),
--(Null, 'Art', 'ART', 'ART 2640', 3, 'Advanced Watercolor Painting', Null, 'ART 1600 or consent of instructor', Null, 'The student will further develop his/her skills and abilities toward a better understanding of the watercolor medium. The student will continue his/her investigation of water-color by viewing slides and films, by reading art books and art periodicals, and by attending galleries and museums followed by periodic class critiques. In the studio, emphasis will be placed on the spontaneity and the immediacy of watercolor while encouraging personal and creative growth.'),
--(Null, 'Art', 'ART', 'ART 2702', 3, 'Sculpture Welding', Null, Null, Null, 'The student will weld and/or braze two or more pieces of sculpture from a list of options including, but not limited to, rod structures, planes over armatures, found objects, and welded forms combined with other media. Creativity is encouraged. Design principles relating to sculpture will be presented orally and visually. Although safety is stressed, equipment is used at the student''s risk. The focus of this course is artistic, not industrial.'),
--(Null, 'Art', 'ART', 'ART 2704', 3, 'Sculpture Casting', Null, Null, Null, 'The student will create two or more pieces of sculpture using casting techniques including, but not limited to, casting hydrostone and polyester resin in plaster molds, metal casting in sand using Styrofoam, and lost wax method. Students should check individual campuses for specific techniques available. Design principles relating to sculpture will be presented orally and visually.'),
--(Null, 'Art', 'ART', 'ART 2710', 3, 'Advanced Figure Drawing', Null, 'ART 2510 or consent of instructor', Null, 'In this class, the student will engage in a series of problem solving assignments pertaining to an in-depth study of the human anatomy as it relates to drawing. This task will be carried out on the part of the student by working with a multimedia format or choosing to concentrate on one medium as a means of self- expression.'),

------Automotive Technology
--(Null, 'Automotive Technology', 'AUT', 'AUT 1000', 4, 'Automotive Fundamentals', 'AUT 1110', Null, Null, 'The course covers how to identify and discuss major automotive systems, components and tools, using the correct terminology. The course will also explore the safe and efficient use of standard automotive tools and equipment during performance of basic automotive servicing procedures. Students will participate in discussions of various automotive employment opportunities and analyze the job entry requirements for each. Students are tested on the following Industry certifications: NC3-Precision Measuring Instruments; Battery Maintenance & Starting; ShopKey Pro Level1; and Torque Theory, Mechanical, and Electrical.'),
--(Null, 'Automotive Technology', 'AUT', 'AUT 1100', 4, 'Automotive Brake Systems Service', 'ATA 1100', Null, Null, 'This course will cover the skills required to properly service the hydraulic brake system, utilizing hands-on training and work experience on licensed vehicles, developing entry-level job skills. The student will rebuild or renew all components of current major automotive manufacturers'' brake systems with an emphasis on safe and proper work habits and procedures.'),
--(Null, 'Automotive Technology', 'AUT', 'AUT 1200', 4, 'Front Suspension & Steering Service', 'ATA 1200', 'AUT 1000', Null, 'This course will develop the skills required to properly service the front suspension and steering system of current model vehicles. A great portion of class time will be spent in the lab rebuilding or renewing all components of the suspension and steering systems. Wheel alignment measurement and correction will be performed by all students on all major automotive equipment, with an emphasis on safe and proper work habits and procedures.'),
--(Null, 'Automotive Technology', 'AUT', 'AUT 1300', 4, 'Automotive Electrical Systems Servicing', 'ATA 1300, TEA 1160', 'AUT 1000 or consent of instructor', Null, 'This course will develop the skills required to service the battery, cranking system, charging system, and electrical accessories systems of all current major automobile manufacturers'' vehicles. Theory of the systems as well as hands-on training will provide job entry-level job skills for the student. Current manufacturers'' specifications as well as safe and proper work habits and procedures will be emphasized.'),
--(Null, 'Automotive Technology', 'AUT', 'AUT 1350', 4, 'Automotive Advanced Electrical and Electronics', Null, 'AUT 1000 and AUT 1300', Null, 'This course develops the skills required to diagnose and service electrical/electronic components. The student will be instructed through a variety of methodologies and instruction to promote discussions related to advanced theories and diagnosis. Advanced training aids and diagnostic tools will be used to enhance knowledge. Multiple vehicles and manufacturer systems will be utilized for advanced troubleshooting; as well as hands-on experience using licensed vehicles. The student will develop advanced-level job skills in diagnosing and repairing malfunctions in the vehicle systems, with an emphasis on safe and proper work practices and procedures.'),
--(Null, 'Automotive Technology', 'AUT', 'AUT 1400', 4, 'Engine Support Systems Servicing', 'ATA 1400, TEA 1110', 'AUT 1000 and AUT 1300 or Consent of Instructor', Null, 'This course will develop the skills required to properly service the engine fuel, lubrication, cooling, exhaust and valve systems. A great portion of the class time will be spent in the laboratory performing tests, as well as repairing and renewing major components of the above named systems. The student will make adjustments, and replace components in accordance with manufacturers'' specifications, with a major emphasis on developing safe and proper work habits and techniques.'),
--(Null, 'Automotive Technology', 'AUT', 'AUT 1500', 4, 'Automotive Tune-Up & Emissions Service', 'ATA 1500, TEA 1140', 'AUT 1000, AUT 1400, and AUT 1300 or consent of instructor', Null, 'This course will develop the skills required to properly tune an engine and diagnose the amount of emissions the engine produces. The student will also calibrate, make adjustments, and renew or replace components of the ignition and emission systems in accordance with the manufacturers'' specifications. The student will also diagnose drive-ability concerns related to engine performance and emissions. Current ignition analysis equipment as well as infrared and other emissions measuring devices and equipment will be used in a safe and proper manner.'),
--(Null, 'Automotive Technology', 'AUT', 'AUT 1600', 4, 'Automotive Transmission Servicing', 'ATA 1600', 'AUT 1300, AUT 1000, or consent of instructor', Null, 'This course will develop the skills required to perform service operations on all current major automobile manufacturers'' automatic transmissions. A major portion of the class time will be spent in the laboratory performing tests, making adjustments, renewing or replacing various components of the transmissions. Manufacturer''s specifications and procedures as well as safe and proper work habits will be greatly emphasized.'),
--(Null, 'Automotive Technology', 'AUT', 'AUT 1700', 4, 'Manual Transmission and Axle Service', 'ATA 1700', 'AUT 1000 or consent of instructor', Null, 'This course will develop the skills required to service all current major automobile manufacturers'' manual transmissions and rear axles. Servicing procedures will include diagnosis, removal and replacement, and rebuilding of the clutch, transmission, drive shaft and the rear axle. Manufacturers'' specifications and procedures as well as safe and proper work habits will be emphasized.'),
--(Null, 'Automotive Technology', 'AUT', 'AUT 1800', 4, 'Automotive Air Conditioning & Heating Service', 'ATA 1800', 'AUT 1300, AUT 1000, or consent of instructor.', Null, 'This course will develop the skills required to service all major automobile manufacturers'' current model heating and air conditioning systems. Theory of the systems as well as work experience on licensed vehicles will be included. The student will develop entry-level job skills in diagnosing and repairing malfunctions in the systems, with an emphasis on safe and proper work habits and procedures.'),
--(Null, 'Automotive Technology', 'AUT', 'AUT 2000', 3, 'Cooperative Internship', 'IND 1403, IND 1403', 'Completion of 24 Automotive (AUT) credits. Consent of Instructor', Null, 'The student will be employed in the automotive servicing industry in a supervised situation under the guidance of a coordinator. The student will identify and describe, through reports and position papers, technical problems encountered on the job. Students will complete a minimum of 135 hours'),
--(Null, 'Automotive Technology', 'AUT', 'AUT 2100', 2, 'Automotive Servicing Special Topics', Null, 'Consent of instructor', Null, 'This course is designed to allow students the opportunity to earn industry related certifications outside of a traditional full course. Instructor authorization is needed to register.'),
--(Null, 'Automotive Technology', 'AUT', 'AUT 2111', 2, 'Automotive Servicing Special Topics', Null, 'Consent of instructor', Null, 'This course is designed to allow students the opportunity to earn industry related certifications outside of a traditional full course. Instructor authorization is needed to register.'),
--(Null, 'Automotive Technology', 'AUT', 'AUT 2112', 2, 'Automotive Servicing Special Topics', Null, 'Consent of instructor', Null, 'This course is designed to allow students the opportunity to earn industry related certifications outside of a traditional full course. Instructor authorization is needed to register.'),
--(Null, 'Automotive Technology', 'AUT', 'AUT 2115', 2, 'Automotive Servicing Special Topics', Null, 'Consent of instructor', Null, 'This course is designed to allow students the opportunity to earn industry related certifications outside of a traditional full course. Instructor authorization is needed to register.'),
--(Null, 'Automotive Technology', 'AUT', 'AUT 2125', 2, 'Automotive Servicing Special Topics', Null, 'Consent of instructor', Null, 'This course is designed to allow students the opportunity to earn industry related certifications outside of a traditional full course. Instructor authorization is needed to register'),

----Biology
--('Global Understanding and Responsibility', 'Biology', 'BIO', 'BIO 1500', 4, 'Environmental Science', Null, Null, Null, 'A laboratory science course which will focus through an interdisciplinary investigation on (a) developing an awareness of one''s total environment (social, physical, and biological), (b) identifying the cause and perspective of our environmental concerns and, (c) exploring the possible and preferred solutions and strategies to those environmental issues.'),
--('Scientific Literacy', 'Biology', 'BIO', 'BIO 1511', 4, 'Life Science', 'LSC 1510, GSC 1510', Null, 'Prerequisites for courses in this department are not automatically waived for College Guest students and students with a bachelor''s degree or higher from a U.S. institution.', 'The course will cover the basic concepts of biology. These include: the cellular basis of life, metabolic processes, genetics, diversity, evolution and ecology, with human applications. This is a laboratory course intended for non-science majors.'),
--('Scientific Literacy', 'Biology', 'BIO', 'BIO 1530', 4, 'Molecular and Cellular Biology', Null, 'Placement into MAT 1100 or higher', 'Prerequisites for courses in this department are not automatically waived for College Guest students and students with a bachelor''s degree or higher from a U.S. institution.', 'The course will cover the molecular and cellular basis of biological processes including metabolism, reproduction, genetics and evolution along with relevant applications of biotechnology. It is expected that students enrolling in this course will have successfully completed both high school biology and chemistry, or equivalent college preparatory work, within the previous five years. This course is the first in a two-semester sequence intended for biology majors. This course includes a laboratory component.'),
--('Scientific Literacy', 'Biology', 'BIO', 'BIO 1560', 4, 'Organismal Biology - Biodiversity, Ecology and Evolution', Null, 'BIO 1511 or BIO 1530 with a ''C'' or better within the last 5 years', 'Prerequisites for courses in this department are not automatically waived for College Guest students and students with a bachelor''s degree or higher from a U.S. institution.', 'This organismal biology course will introduce the basic scientific principles underlying the biodiversity, ecology and evolution of representative species from various fungi, plant, animal and other eukaryotic taxa. Topics covered will include fundamentals of evolutionary theory; systematics and taxonomic classification; a comparative study of the structure, function and evolutionary relationships among eukaryotic species; and ecological topics including population biology, communities and ecosystems. This course is the second in a two-semester sequence intended for biology majors. This course includes a laboratory component.'),
--('Scientific Literacy', 'Biology', 'BIO', 'BIO 1570', 3, 'Microbiology of Health and Disease', 'BIO 1710', 'A grade ''C'' or better in BIO 1511 or BIO 1530 in the last 5 years', 'Prerequisites for courses in this department are not automatically waived for College Guest students and students with a bachelor''s degree or higher from a U.S. institution.', 'Student will study the general nature and behavior of microbes as applied to human health and disease, including the dynamics of normal microbiota, the infectious process, microbes as causative agents of disease, host parasite relationships and development of immunity. Particular emphasis will be placed on the study of various modes of transmission and proper management to prevent spreading of infectious disease. This natural science course is also required for many health-related fields. This is a non-lab course.'),
--('Scientific Literacy', 'Biology', 'BIO', 'BIO 1600', 3, 'Human Structure and Function', Null, Null, Null, 'This course is designed to give the student a basic understanding of the human body. Visual demonstrations and a variety of organ and system models will be used during lectures to illustrate the structural and functional organization of the human body. This natural science course is also required for many health profession and technology programs. This is a non-lab course.'),
--(Null, 'Biology', 'BIO', 'BIO 1650', 5, 'Human Anatomy and Physiology for the Emergency Medical Services Program', Null, 'Prerequisite: Completion of EMS 1010 EMS 1020 and EMS 1100 each with a grade of ''C'' or better.', 'Note: Prerequisites for courses in this department are not automatically waived for College Guest students and studentswith a bachelor''s degree or higher from a U.S. institution.', 'This course is designed to meet the needs of students in the Emergency Medical Services program. This course reinforces the fundamentals of human anatomy and physiology for all major body systems with a detailed laboratory experience. The goal of this course is to provide a detailed survey of human anatomy and physiology to students in the Emergency Medical Services program. Students will learn basic terminology associated with human anatomical structures and physiological processes. Students will apply terminology and physiological function through the use of models, plaques, microscopy, dissection and experimentation in lab. This course does not meet the requirements for most other health professional programs.'),
--('Scientific Literacy', 'Biology', 'BIO', 'BIO 2540', 4, 'General Zoology', Null, 'BIO 1530 with a ''C'' or better within the last 5 years', 'Prerequisites for courses in this department are not automatically waived for College Guest students and students with a bachelor''s degree or higher from a U.S. institution.', 'The course will explore representative protozoa and members of the animal kingdom, emphasizing their metabolism, anatomical structure and function, reproduction and development, evolution, diversity and ecology. The laboratory component of this course, which may include animal dissection, involves the application of the terminology and concepts presented in lecture.'),
--(Null, 'Biology', 'BIO', 'BIO 2560', 3, 'Principles of Genetics', Null, 'BIO 1530 and any of the following: BIO 1560 BIO 2540 or BIO 2710 all with a grade of ''C'' or better within the last 5 years or consent of instructor', 'Prerequisites for courses in this department are not automatically waived for College Guest students and students with a bachelor''s degree or higher from a U.S. institution.', 'The course examines the Mendelian and non-Mendelian laws of inheritance, the chromosome theory, chromosomal and genetic mutations, mechanisms of gene action, the nature of genetic material, statistical analysis, and eugenics. This is a non-laboratory course.'),
--(Null, 'Biology', 'BIO', 'BIO 2602', 2, 'Special Topics in Biology: Biodiversity in the Tropics', 'BIO 1500 BIO 1530 or BIO 1511', Null, 'Prerequisites for courses in this department are not automatically waived for College Guest students and students with a bachelor''s degree or higher from a U.S. institution.', 'Biodiversity in the Tropics.'),
--(Null, 'Biology', 'BIO', 'BIO 2630', 4, 'Human Anatomy and Physiology I', 'BIO 1630, BIO 1610', 'Satisfactory score on the OCC Biology Proficiency Test; or a grade of ''C'' or better in BIO 1511 or BIO 1530 (or equivalent college transfer course).', 'Prerequisites for courses in this department are not automatically waived for College Guest students and students with a bachelor''s degree or higher from a U.S. institution.', 'This course will analyze the structural and functional relationships of the human body at the biochemical, cellular, tissue, organ and system level. Emphasis will be placed on the identification of the major anatomical parts and physiological activities of the integumentary, skeletal (including articulations), muscular, and nervous (including special senses) system. The laboratory component of this course involves application of the concepts presented in lecture. This natural science course is also required for many health-related fields.'),
--(Null, 'Biology', 'BIO', 'BIO 2640', 4, 'Human Anatomy and Physiology II', 'BIO 1640, BIO 1620', 'Satisfactory score on the OCC Biology Proficiency Test; or a grade of ''C'' or better in BIO 1511 or BIO 1530 (or equivalent college transfer course).', 'Prerequisites for courses in this department are not automatically waived for College Guest students and students with a bachelor''s degree or higher from a U.S. institution.', 'Utilizing and building upon information covered in Human Anatomy and Physiology I (BIO 2630), this course will identify the major anatomical parts of the endocrine, cardiovascular, lymphatic, immune, respiratory, digestive, urinary, and reproductive systems of the human body and relate their structures to the physiological activities of these systems. This course will also analyze the homeostatic effects of fluids, electrolytes, acids and bases throughout the integrated human body. The laboratory component of this course involves application of the concepts presented in lecture. This natural science course is also required for most health profession and technology programs such as: dental hygiene, respiratory therapy, surgical technology and nursing.'),
--(Null, 'Biology', 'BIO', 'BIO 2660', 3, 'Pathophysiology', 'BIO 2250', 'BIO 1650 or BIO 2640 with a grade of ''C'' or better within the last 5 years or consent of discipline or department designee.', 'Prerequisites for courses in this department are not automatically waived for College Guest students and students with a bachelor''s degree or higher from a U.S. institution.', 'This course teaches the fundamentals of pathophysiology as it relates to care of the chronic and emergent patient in home, pre-hospital, and hospital settings. Content includes an overview of normal body functions, the immune system and immune response, discussion of specific diseases, cellular injury and death, shock, and how disease and injury alter normal function. This course is intended to meet the requirements of the EMS National standard Curriculum on pathophysiology and is part of the Advanced EMT program.'),
--(Null, 'Biology', 'BIO', 'BIO 2710', 4, 'Microbiology', Null, 'Both BIO 1530 and CHE 1000 or higher (or equivalent college transfer course) with a grade of ''C'' or better within the last 5 years; or consent of department discipline designee.', 'Prerequisites for courses in this department are not automatically waived for College Guest students and students with a bachelor''s degree or higher from a U.S. institution.', 'The course concepts include microbial cell biology, microbial genetics, interactions and impact of microorganisms and humans, interactions and impact of microorganisms in the environment, and microbial diversity. Laboratory incorporates basic techniques and exercises to investigate course concepts. This natural science course is also required for many health profession and technology programs such as: respiratory therapy, surgical technology and nursing.');

(Null, 'Business', 'BUS', 'BUS 1010', 4, 'Introduction to Business', 'BUS 1010', Null, Null, 'This introductory business class covers the fundamentals of business including free market economics, ethics/social responsibility, entrepreneurship, management, human resource management, marketing, supply chain, finance, information systems, accounting, and government's role in business. All topics are approached in the context of a global business environment'),
(Null, 'Business', 'BUS', 'BUS 1210', 3, 'Small Business Basics', Null, Null, Null, 'This course examines the factors necessary to start a small business and enhance the likelihood of its success. Topics of study include assessment of the entrepreneurial personality and the suitability of small business as a career, assessing market potential, conducting a feasibility analysis/writing a business plan, raising capital and managing both finances and credit, implementing marketing and management strategies (including risk management, taxes, and record-keeping), and responding to government regulation.'),
(Null, 'Business', 'BUS', 'BUS 1310', 3, 'Supervision', Null, Null, Null, 'This course examines principles of supervision such as induction, training, disciplining, absenteeism, safety, waste, control, equipment layout, grievance control, production control, and time study.'),
(Null, 'Business', 'BUS', 'BUS 1400', 3, 'Investment Fundamentals', Null, Null, Null, 'This course examines common and preferred stocks, corporate and municipal bonds, mutual funds, cash instruments, and U.S. Treasuries, as they relate to personal investing. Additionally, this course will also examine types of exchanges, ways to analyze corporate financial statements, and economic forecasting.'),

(Null, 'Business', 'BUS', 'BUS 1410', 3, 'Personal Finance', Null, Null, Null, 'This course examines financial planning principles and proper money management for wealth accumulation. Topics of study include saving and budgeting for the short and long term, managing debt and credit, making major purchases (e.g. auto, home), estate and retirement planning, and investing fundamentals.'),
(Null, 'Business', 'BUS', 'BUS 1450', 3, 'Internship/Co-op I', 'BUS 1423', 'OCC student with at least 24 credits including 12 credits in business or retailing. Consent of Instructor.', Null, 'The internship student will be employed in a position of responsibility as a supervisor or management trainee in a specific business within the student's career field.'),
(Null, 'Business', 'BUS', 'BUS 2030', 3, 'Business Law I', 'BUS 2010', Null, Null, 'This course examines the legal environment of business including the nature of law and dispute resolutions in the United States. Specific topics include court procedure, alternative dispute resolution, constitutional rights, intellectual property, torts, crimes, business ethics, contracts, and sales under the Uniform Commercial Code.'),

(Null, 'Business', 'BUS', 'BUS ', 4, '', Null, Null, Null, ''),
(Null, 'Business', 'BUS', 'BUS ', 4, '', Null, Null, Null, ''),
(Null, 'Business', 'BUS', 'BUS ', 4, '', Null, Null, Null, ''),
(Null, 'Business', 'BUS', 'BUS ', 4, '', Null, Null, Null, ''),
(Null, 'Business', 'BUS', 'BUS ', 4, '', Null, Null, Null, ''),
(Null, 'Business', 'BUS', 'BUS ', 4, '', Null, Null, Null, ''),


----(Null, 'Business', 'BUS', 'BUS ', 4, '', Null, Null, Null, ''),



--(Null, 'Art', 'ART', 'ART ', 3, '', Null, Null, Null, ''),
--(Null, 'Art', 'ART', 'ART ', 3, '', Null, Null, Null, ''),

--(Null, 'Art', 'ART', 'ART ', 3, '', Null, Null, Null, ''),
--(Null, 'Art', 'ART', 'ART ', 3, '', Null, Null, Null, ''),


--(Null, 'Art', 'ART', 'ART ', 3, '', Null, Null, Null, ''),

--(Null, '', '', ' ', 2, '', '', Null, Null,, '');